# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mash < Formula
  desc ""
  homepage "https://github.com/dennisbergevin/homebrew-tools"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dennisbergevin/mash/releases/download/v0.1.1/mash_Darwin_x86_64.tar.gz"
      sha256 "1eed2610d0f8f747ef59d06b1a6da506de4765ace4da8529a3c3d40ca375dd8b"

      def install
        bin.install "mash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dennisbergevin/mash/releases/download/v0.1.1/mash_Darwin_arm64.tar.gz"
      sha256 "2bec0090d2091210ddbbc375936850752a63cf7ebb3f47c4d17d4285e8b5312f"

      def install
        bin.install "mash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/dennisbergevin/mash/releases/download/v0.1.1/mash_Linux_x86_64.tar.gz"
      sha256 "f101998f7b7168afb27f7738475bc9dc5c1e4bec6f85aa691bee4848b06a3ab2"
      def install
        bin.install "mash"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/dennisbergevin/mash/releases/download/v0.1.1/mash_Linux_arm64.tar.gz"
      sha256 "f4f4c5c97854c988dd9a46c3118d016974954e5009205af1bdb3ea04063e3320"
      def install
        bin.install "mash"
      end
    end
  end
end
