# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mash < Formula
  desc ""
  homepage "https://github.com/dennisbergevin/homebrew-tools"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dennisbergevin/mash/releases/download/v0.1.0/mash_Darwin_x86_64.tar.gz"
      sha256 "5e004df4429202551981c9c2f478a1cc6ff9ede10fa7676ec186c159ebe8c7f3"

      def install
        bin.install "mash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dennisbergevin/mash/releases/download/v0.1.0/mash_Darwin_arm64.tar.gz"
      sha256 "1930f7f1210f4c96efd084182cff2aca0f726504c72076f08e48d1d22c3e6116"

      def install
        bin.install "mash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/dennisbergevin/mash/releases/download/v0.1.0/mash_Linux_x86_64.tar.gz"
      sha256 "a3c8614ea62ec2d02e2542672151b8564c8058ee890106bc5f055013498abcf6"
      def install
        bin.install "mash"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/dennisbergevin/mash/releases/download/v0.1.0/mash_Linux_arm64.tar.gz"
      sha256 "104c0f05158aaf4f28a8ec9f7e327a9f2b58988066602b9d4eeac5177ee9bbf0"
      def install
        bin.install "mash"
      end
    end
  end
end
