# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pwgo < Formula
  desc ""
  homepage "https://github.com/dennisbergevin/homebrew-tools"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dennisbergevin/pwgo/releases/download/v0.1.1/pwgo_Darwin_x86_64.tar.gz"
      sha256 "98e160e911dc59049592af4d252981c9099846479b4753dc3cce56121a4061e2"

      def install
        bin.install "pwgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dennisbergevin/pwgo/releases/download/v0.1.1/pwgo_Darwin_arm64.tar.gz"
      sha256 "93624b3672df4020bb36bfa177b2a120206b6effd7ae91ecfb64d07e3f446213"

      def install
        bin.install "pwgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/dennisbergevin/pwgo/releases/download/v0.1.1/pwgo_Linux_x86_64.tar.gz"
      sha256 "bffe9182a95e90df233c5a63b49f7740dc2c83eced16dfa8030dc60931034568"
      def install
        bin.install "pwgo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/dennisbergevin/pwgo/releases/download/v0.1.1/pwgo_Linux_arm64.tar.gz"
      sha256 "8fa602a936ced1b6d89c7bf3693c0121bdf423647be2c2b07252f44736f69a14"
      def install
        bin.install "pwgo"
      end
    end
  end
end
