# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pwgo < Formula
  desc ""
  homepage "https://github.com/dennisbergevin/homebrew-tools"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dennisbergevin/pwgo/releases/download/v0.1.0/pwgo_Darwin_x86_64.tar.gz"
      sha256 "aa3f2b5065d1a363817e17a18d2ffb66b4e5d024da7324e7830ad4040cf9c8d5"

      def install
        bin.install "pwgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dennisbergevin/pwgo/releases/download/v0.1.0/pwgo_Darwin_arm64.tar.gz"
      sha256 "cfee225b385ebe8f90ae61cac4b256f71c1d3dcbe32921ba75cdb036e26b7a11"

      def install
        bin.install "pwgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/dennisbergevin/pwgo/releases/download/v0.1.0/pwgo_Linux_x86_64.tar.gz"
      sha256 "82d19f9b22bdc5bc3d5c842e2cb57159abd6650365d0221b199165a874c99d5f"
      def install
        bin.install "pwgo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/dennisbergevin/pwgo/releases/download/v0.1.0/pwgo_Linux_arm64.tar.gz"
      sha256 "4a54c8e97b7a94672f8b78b10fafd5d22ec08bfbd28cf6f56404b6ff96390fb0"
      def install
        bin.install "pwgo"
      end
    end
  end
end
