# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pwtree < Formula
  desc ""
  homepage "https://github.com/dennisbergevin/homebrew-tools"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dennisbergevin/pwtree/releases/download/v0.1.2/pwtree_Darwin_x86_64.tar.gz"
      sha256 "2a5f67bfe5c16f7d0802b3b3ac4e6edc64346d15fa7c7c8da103acd26e0fda3a"

      def install
        bin.install "pwtree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dennisbergevin/pwtree/releases/download/v0.1.2/pwtree_Darwin_arm64.tar.gz"
      sha256 "50be27109584f9369be07b3aaa47ffc97572be1e8ad10fcbc800f27726d47a8c"

      def install
        bin.install "pwtree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/dennisbergevin/pwtree/releases/download/v0.1.2/pwtree_Linux_x86_64.tar.gz"
      sha256 "6fa79359d26949f763bd74313962349833894391c1038caa97c401468db26edf"
      def install
        bin.install "pwtree"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/dennisbergevin/pwtree/releases/download/v0.1.2/pwtree_Linux_arm64.tar.gz"
      sha256 "c741de18447fb9f27aaea61d2d5131639e4de70be48f1631e1399e63858d0fdc"
      def install
        bin.install "pwtree"
      end
    end
  end
end
