# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pwtree < Formula
  desc ""
  homepage "https://github.com/dennisbergevin/homebrew-tools"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dennisbergevin/pwtree/releases/download/v0.1.5/pwtree_Darwin_x86_64.tar.gz"
      sha256 "4ed5435a7f4af6acc54f746f031925ed472df515b9949b4904017e02dfb6fcb6"

      def install
        bin.install "pwtree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dennisbergevin/pwtree/releases/download/v0.1.5/pwtree_Darwin_arm64.tar.gz"
      sha256 "82c300bb1ae102dc6509dcd29673ab71e7f5b4c5dc48d28bae96810cc2f1fb9d"

      def install
        bin.install "pwtree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/dennisbergevin/pwtree/releases/download/v0.1.5/pwtree_Linux_x86_64.tar.gz"
      sha256 "d8c1a020090232ac07c75d5f8a0a69ed12d11936cabe4c45c1f3d738bbf6b780"
      def install
        bin.install "pwtree"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/dennisbergevin/pwtree/releases/download/v0.1.5/pwtree_Linux_arm64.tar.gz"
      sha256 "f5326b24e70de468dd0810bd6ac14b687ed98206bd8f8e716a69fae9bdaeb950"
      def install
        bin.install "pwtree"
      end
    end
  end
end
